package com.lan._1utils._2collectionmap.listmap;

import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TestStaticData {

    public static List<Map<String, Object>> listMapOut = Arrays.asList(
            new HashMap<String, Object>(2){{ put("id",1); put("grid_code","v2"); }},
            new HashMap<String, Object>(2){{ put("id",2); put("grid_code","v22"); }},
            new HashMap<String, Object>(2){{ put("id",3); put("grid_code","v23"); }},
            new HashMap<String, Object>(2){{ put("id",4); put("grid_code","v24"); }},
            new HashMap<String, Object>(2){{ put("id",5); put("grid_code","v25"); }}
    );

    public static List<Map<String, Object>> listMapIn3 = Arrays.asList(
            new HashMap<String, Object>(2){{ put("id","1"); put("grid_path","v2"); }},
            new HashMap<String, Object>(2){{ put("id","3"); put("grid_path","v23"); }},
            new HashMap<String, Object>(2){{ put("id","5"); put("grid_path","v25"); }}
    );

    // listMapOut 的儿子  模拟一对多。 用set合并重复数据
    public static List<Map<String, Object>> listMapIn5 = Arrays.asList(
            new HashMap<String, Object>(2){{ put("id","1"); put("grid_path","v2");  put("key_id",1); }},
            new HashMap<String, Object>(2){{ put("id","5"); put("grid_path","不放大");  put("key_id",1); }},
            new HashMap<String, Object>(2){{ put("id","31"); put("grid_path","v2fsdf3");  put("key_id",2); }},
            new HashMap<String, Object>(2){{ put("id","32"); put("grid_path","v2fsdf3");  put("key_id",3); }},
            new HashMap<String, Object>(2){{ put("id","33"); put("grid_path","vfsdf");  put("key_id",1); }},
            new HashMap<String, Object>(2){{ put("id","34"); put("grid_path","dsf");  put("key_id",4); }},
            new HashMap<String, Object>(2){{ put("id","35"); put("grid_path","fsdf");  put("key_id",3); }},
            new HashMap<String, Object>(2){{ put("id","36"); put("grid_path","策");  put("key_id",1); }},
            new HashMap<String, Object>(2){{ put("id","37"); put("grid_path","大幅度发");  put("key_id",4); }},
            new HashMap<String, Object>(2){{ put("id","5"); put("grid_path","不放大");  put("key_id",1); }}
    );

    // listMapOut 的er儿子  模拟多对一 或者 一对一  这种情况，由于是从方，所有模拟主方一点是五条，而且不一样
    public static List<Map<String, Object>> listMapIn6 = Arrays.asList(
            new HashMap<String, Object>(3){{ put("id","1"); put("path","v2");  put("key_id2",1); }},
            new HashMap<String, Object>(3){{ put("id","31"); put("ath","v2fsdf3");  put("key_id2",2); }},
            new HashMap<String, Object>(3){{ put("id","32"); put("path","v2fsdf3");  put("key_id2",3); }},
            new HashMap<String, Object>(3){{ put("id","34"); put("path","dsf");  put("key_id2",4); }},
            new HashMap<String, Object>(3){{ put("id","5"); put("path","不放大");  put("key_id2",5); }}
    );


    public static List<Map<String, Object>> listMapIn = Arrays.asList(
            new HashMap<String, Object>(2){{ put("collect_month",9); put("totalnum","v2"); }},
            new HashMap<String, Object>(2){{ put("collect_month",2); put("totalnum","v22你好"); }},
            new HashMap<String, Object>(2){{ put("collect_month",7); put("totalnum","v23"); }},
            new HashMap<String, Object>(2){{ put("collect_month",4); put("totalnum","v24"); }},
            new HashMap<String, Object>(2){{ put("collect_month",5); put("totalnum","v25"); }}
    );

    public static List<Map<String, Object>> listMapIn2 = Arrays.asList(
            new HashMap<String, Object>(){{ put("company","湘潭县运输有限公司"); put("type","县内"); put("car","湘C57361~(湘潭县汽车站-湘潭县茶恩寺),湘C56883~(湘潭县方上桥-湘潭县汽车站),湘C58072~(湘潭县郭家桥-湘潭县汽车站),湘C57563~(湘潭县汽车站-湘潭县茶恩寺),湘C59656~(湘潭县茶恩寺-湘潭县汽车站),湘C58733~(湘潭县茶恩寺-湘潭县汽车站),湘C57560~(湘潭县汽车站-湘潭县茶恩寺),湘C57876~(湘潭县汽车站-湘潭县花石),湘C56797~(湘潭县石鼓-湘潭县汽车站),湘C58113~(湘潭县汽车站-湘潭县郭家桥),湘C58727~(湘潭县联兴-湘潭县汽车站),湘C56799~(湘潭县花石-湘潭县汽车站),湘C58010~(湘潭县茶恩寺-湘潭县汽车站),湘C58300~(湘潭县日华-湘潭县花石),湘C56776~(湘潭县楠竹山-湘潭县汽车站),湘C58017~(湘潭县汽车站-湘潭县金石),湘C58033~(湘潭县汽车站-湘潭县茶恩寺),湘C57698~(湘潭县东风水库-湘潭县汽车站),湘C57892~(湘潭县金石-湘潭县汽车站),湘C58083~(湘潭县汽车站-湘潭县郭家桥),湘C58128~(湘潭县大坟山-湘潭县汽车站),湘C58705~(湘潭县汽车站-湘潭县花石),湘C58082~(湘潭县花石-湘潭县汽车站),湘C58719~(湘潭县花石-湘潭县汽车站),湘C58037~(湘潭县花石-湘潭县汽车站),湘C58199~(湘潭县花石-湘潭县汽车站),湘C55868~(湘潭县汽车站-湘潭县石潭),湘C58036~(湘潭县梅市-湘潭县汽车站),湘C57591~(湘潭县龙口石膏矿-湘潭县汽车站),湘C58265~(湘潭县花石-湘潭县汽车站),湘C58081~(湘潭县花石-湘潭县汽车站),湘C57795~(湘潭县花石-湘潭县汽车站),湘C57158~(湘潭县石坝-湘潭县汽车站),湘C58097~(湘潭县汽车站-湘潭县花石),湘C58089~(湘潭县花石-湘潭县汽车站),湘C56833~(湘潭县景泉-湘潭县汽车站),湘C56159~(湘潭县汽车站-湘潭县黄荆坪),湘C58702~(湘潭县汽车站-湘潭县盐埠),湘C58291~(湘潭县汽车站-湘潭县茶恩寺),湘C58189~(湘潭县茶恩寺-湘潭县汽车站),湘C58193~(湘潭县汽车站-湘潭县茶恩寺),湘C58109~(湘潭县高塘-湘潭县汽车站)"); }},
            new HashMap<String, Object>(){{ put("company","湘潭县运输有限公司"); put("type","县际"); put("car","湘C56910~(湘潭县石潭-湘潭市汽车西站),湘C57069~(湘潭县瓦叶塘-湘潭市汽车西站),湘C56880~(湘潭县石潭-湘潭市汽车西站),湘C59823~(湘潭县汽车站-湘乡市泉塘),湘C58255~(湘潭县美德桥-湘潭市汽车西站),湘C56735~(湘潭县龙口石膏矿-湘潭市汽车西站),湘C57066~(湘潭县湘河村-湘潭市汽车西站),湘C57706~(湘乡市石坝-湘乡市汽车站),湘C57598~(湘潭县金星-湘潭市汽车西站),湘C57697~(湘潭县双马-湘潭市汽车西站),湘C57693~(湘潭县高泉-湘潭市汽车西站),湘C57681~(湘潭县毛塘坝-湘潭市汽车西站),湘C57528~(湘潭县四美-湘潭市汽车西站),湘C58277~(湘潭市紫山-湘潭市汽车西站),湘C58086~(湘潭县磷矿-湘潭市汽车西站),湘C56876~(湘潭县荆洲-湘潭市汽车西站),湘C57053~(湘潭县花桥-湘潭市汽车西站),湘C59736~(湘潭县盐埠-湘潭市汽车西站),湘C58263~(湘潭县盐埠-湘潭市汽车西站),湘C59679~(湘潭县盐埠-湘潭市汽车西站),湘C57215~(湘潭县景泉-湘潭市汽车西站),湘C57150~(湘潭县景泉-湘潭市汽车西站),湘C57678~(湘潭县黄荆坪-湘潭市汽车西站),湘C58237~(湘潭县黄荆坪-湘潭市汽车西站),湘C57858~(湘潭县黄荆坪-湘潭市汽车西站),湘C58191~(湘潭县斗子塘-湘潭市汽车西站),湘C56736~(湘潭市汽车西站-湘潭县日华),湘C57032~(湘潭县黄荆坪-湘潭市汽车西站)"); }},
            new HashMap<String, Object>(){{ put("company","湘潭县公共汽车有限责任公司"); put("type","县内"); put("car","湘C58821~(湘潭县汽车站-湘潭县石鼓),湘C58826~(湘潭县汽车站-湘潭县茶恩寺),湘C58775~(湘潭县汽车站-湘潭县茶恩寺),湘C56501~(湘潭县茶恩寺-湘潭县汽车站),湘C57638~(湘潭县茅亭-湘潭县汽车站)"); }},
            new HashMap<String, Object>(){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car","湘C75115~(湘乡市红石-湘乡市汽车站),湘C77028~(湘乡市大杉-湘乡市汽车站),湘C76280~(湘乡市高维-湘乡市汽车站),湘C77785~(湘乡市大乐-湘乡市汽车站),湘C75992~(湘乡市九雁塘-湘乡市汽车站),湘C73265~(湘乡市马坪-湘乡市汽车站),湘C76256~(湘乡市棋梓-湘乡市汽车站),湘C75220~(湘乡市汽车站-湘乡市棋梓),湘C77787~(湘乡市洪塘-湘乡市汽车站),湘C77029~(湘乡市桂花-湘乡市汽车站),湘C75255~(湘乡市汽车站-湘乡市棋梓),湘C75111~(湘乡市汽车站-湘乡市棋梓),湘C75032~(湘乡市汽车站-湘乡市棋梓),湘C75221~(湘乡市棋梓-湘乡市汽车站),湘C77737~(湘乡市棋梓-湘乡市汽车站),湘C75095~(湘乡市棋梓-湘乡市汽车站),湘C73562~(湘乡市马坪-湘乡市汽车站),湘C73687~(湘乡市马坪-湘乡市汽车站),湘C73882~(湘乡市汽车站-湘乡市横铺),湘C75213~(湘乡市横铺-湘乡市汽车站),湘C77858~(湘乡市横铺-湘乡市汽车站),湘C75972~(湘乡市汽车站-湘乡市壶天),湘C75075~(湘乡市棋梓-湘乡市汽车站),湘C75228~(湘乡市汽车站-湘乡市棋梓),湘C76268~(湘乡市棋梓-湘乡市汽车站),湘C75300~(湘乡市棋梓-湘乡市汽车站),湘C76283~(湘乡市日新-湘乡市岐山),湘C73708~(湘乡市岐山-湘乡市汽车站),湘C73569~(湘乡市汽车站-湘乡市金龙),湘C73679~(湘乡市汽车站-湘乡市马坪),湘C75031~(湘乡市壶天-湘乡市汽车站),湘C77786~(湘乡市壶天-湘乡市汽车站),湘C76269~(湘乡市石桥-湘乡市汽车站),湘C78038~(湘乡市壶天-湘乡市汽车站),湘C75851~(湘乡市壶天-湘乡市汽车站),湘C75583~(湘乡市汽车站-湘乡市毛田),湘C75862~(湘乡市壶天南岳-湘乡市日新),湘C75879~(湘乡市壶天南岳-湘乡市汽车站),湘C76257~(湘乡市月山湾-湘乡市汽车站),湘C77105~(湘乡市朝阳-湘乡市汽车站),湘C75231~(湘乡市桂花-湘乡市汽车站),湘C75239~(湘乡市汽车站-湘乡市棋梓),湘C77763~(湘乡市壶天-湘乡市汽车站),湘C79088~(湘乡市壶天-湘乡市汽车站),湘C75096~(湘乡市汽车站-湘乡市棋梓),湘C76265~(湘乡市酒铺-湘乡市汽车站),湘C75181~(湘乡市汽车站-湘乡市横铺),湘C75260~(湘乡市汽车站-湘乡市马坪),湘C75850~(湘乡市壶天-湘乡市汽车站),湘C75805~(湘乡市壶天-湘乡市汽车站),湘C77118~(湘乡市汽车站-湘乡市壶天),湘C79588~(湘乡市汽车站-湘乡市壶天),湘C75967~(湘乡市汽车站-湘乡市壶天),湘C76281~(湘乡市壶天-湘乡市汽车站),湘C75986~(湘乡市壶天-湘乡市汽车站),湘C75963~(湘乡市壶天-湘乡市汽车站),湘C75293~(湘乡市壶天-湘乡市汽车站),湘C78088~(湘乡市壶天-湘乡市汽车站),湘C75261~(湘乡市壶天-湘乡市汽车站),湘C78338~(湘乡市壶天-湘乡市汽车站),湘C75305~(湘乡市石坝-湘乡市汽车站),湘C76935~(湘乡市石桥-湘乡市汽车站),湘C75803~(湘乡市马坪-湘乡市汽车站),湘C75102~(湘乡市邓氏路口-湘乡市汽车站),湘C75925~(湘乡市云居-湘乡市汽车站),湘C75876~(湘乡市枚下-湘乡市汽车站),湘C75296~(湘乡市壶天-湘乡市汽车站),湘C78278~(湘乡市壶天-湘乡市汽车站),湘C75859~(湘乡市汽车站-湘乡市苏坡),湘C79668~(湘乡市汽车站-湘乡市苏坡),湘C77790~(湘乡市壶天-湘乡市汽车站),湘C75009~(湘乡市汽车站-湘乡市横铺),湘C76253~(湘乡市汽车站-湘乡市曾家山),湘C73666~(湘乡市壶天-湘乡市汽车站),湘C75205~(湘乡市汽车站-湘乡市棋梓),湘C75223~(湘乡市棋梓-湘乡市汽车站),湘C75106~(湘乡市棋梓-湘乡市汽车站),湘C75866~(湘乡市低坪-湘乡市汽车站),湘C76239~(湘乡市杜家坪-湘乡市汽车站),湘C76952~(湘乡市毛田-湘乡市汽车站),湘C77163~(湘乡市壶天合东-湘乡市汽车站),湘C76231~(湘乡市石桥-湘乡市汽车站),湘C73925~(湘乡市棋梓-湘乡市汽车站),湘C75332~(湘乡市棋梓-湘乡市汽车站),湘C75130~(湘乡市棋梓-湘乡市汽车站),湘C73933~(湘乡市横铺-湘乡市汽车站),湘C73612~(湘乡市壶天-湘乡市汽车站),湘C75991~(湘乡市汽车站-湘乡市九雁塘),湘C75856~(湘乡市邓氏路口-湘乡市汽车站),湘C75326~(湘乡市日新-湘乡市岐山),湘C77005~(湘乡市汽车站-湘乡市毛田),湘C76983~(湘乡市石坝-湘乡市汽车站),湘C76375~(湘乡市汽车站-湘乡市青皮),湘C76936~(湘乡市汽车站-湘乡市清江),湘C76926~(湘乡市汽车站-湘乡市清江),湘C76520~(湘乡市白银村-湘乡市汽车站),湘C73936~(湘乡市大湖-湘乡市汽车站),湘C76273~(湘乡市日新-湘乡市岐山),湘C75837~(湘乡市翻江-湘乡市棋梓),湘C76232~(湘乡市棋梓-湘乡市曾家山),湘C76221~(湘乡市棋梓-湘乡市曾家山),湘C75865~(湘乡市月山湾-湘乡市汽车站),湘C76212~(湘乡市岐山-湘乡市汽车站),湘C76925~(湘乡市岐山-湘乡市汽车站),湘C76913~(湘乡市榨坪-湘乡市汽车站),湘C76311~(湘乡市马龙-湘乡市汽车站),湘C76292~(湘乡市汽车站-湘乡市楠竹口),湘C75987~(湘乡市汽车站-湘乡市月山湾),湘C77721~(湘乡市汽车站-湘乡市南郑),湘C78028~(湘乡市月山湾-湘乡市汽车站),湘C79888~(湘乡市汽车站-湘乡市茶杯),湘C77195~(湘乡市石桥-湘乡市汽车站),湘C77782~(湘乡市石桥-湘乡市汽车站),湘C75067~(湘乡市汽车站-湘乡市大杉),湘C75982~(湘乡市新跃-湘乡市汽车站),湘C77038~(湘乡市汽车站-湘乡市桂花),湘C77023~(湘乡市汽车站-湘乡市朝阳),湘C73508~(湘乡市于塘-湘乡市汽车站),湘C76985~(湘乡市小车-湘乡市汽车站),湘C76276~(湘乡市棋梓-湘乡市汽车站),湘C75266~(湘乡市汽车站-湘乡市棋梓),湘C75371~(湘乡市棋梓-湘乡市汽车站),湘C75265~(湘乡市棋梓-湘乡市汽车站),湘C75316~(湘乡市棋梓-湘乡市汽车站),湘C75207~(湘乡市棋梓-湘乡市汽车站),湘C75091~(湘乡市汽车站-湘乡市棋梓),湘C75076~(湘乡市汽车站-湘乡市棋梓),湘C75007~(湘乡市汽车站-湘乡市棋梓),湘C75020~(湘乡市棋梓-湘乡市汽车站),湘C73885~(湘乡市横铺-湘乡市汽车站),湘C77771~(湘乡市横铺-湘乡市汽车站),湘C75199~(湘乡市汽车站-湘乡市横铺),湘C75538~(湘乡市汽车站-湘乡市横铺),湘C73685~(湘乡市汽车站-湘乡市马坪),湘C75129~(湘乡市白石-湘乡市汽车站),湘C75869~(湘乡市马坪-湘乡市汽车站),湘C75125~(湘乡市汽车站-湘乡市马坪),湘C75192~(湘乡市汽车站-湘乡市马坪),湘C75126~(湘乡市汽车站-湘乡市马坪)"); }},
            new HashMap<String, Object>(){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县际"); put("car","湘C75107~(湘乡市汽车站-湘潭市汽车西站),湘C73951~(湘乡市汽车站-湘潭市汽车西站),湘C76991~(湘乡市泉塘-湘潭县汽车站),湘C77158~(湘乡市泉塘-湘潭县汽车站),湘C75169~(湘乡市汽车站-湘潭市汽车西站),湘C75258~(湘乡市汽车站-湘潭市汽车西站),湘C72502~(湘乡市汽车站-湘潭市汽车西站),湘C76275~(湘潭县茶佩-湘潭市汽车西站),湘C75910~(湘乡市毛田-湘潭市汽车西站),湘C75285~(湘乡市汽车站-湘潭市汽车西站),湘C75282~(湘乡市汽车站-湘潭市汽车西站),湘C73972~(湘乡市汽车站-湘潭市汽车西站),湘C78528~(湘乡市坪花-湘潭市汽车西站),湘C75552~(湘乡市白云石矿-湘潭市下摄司),湘C73521~(湘潭县歇马-湘潭市株易路口),湘C75182~(湘乡市马坪-湘潭市汽车西站),湘C75283~(湘乡市汽车站-湘潭市汽车西站),湘C78378~(湘潭县环山-湘潭市汽车西站),湘C76698~(湘乡市水府庙-湘潭市汽车西站),湘C77136~(湘乡市泉塘-湘潭县汽车站),湘C76323~(湘乡市泉塘-湘潭县汽车站),湘C75225~(湘乡市汽车站-湘潭市汽车西站),湘C75317~(湘乡市汽车站-湘潭市汽车西站),湘C75299~(湘乡市汽车站-湘潭市汽车西站),湘C75127~(湘乡市汽车站-湘潭市汽车西站),湘C73702~(湘乡市汽车站-湘潭县汽车站),湘C77008~(湘乡市汽车站-湘潭县汽车站),湘C76391~(湘乡市汽车站-湘潭县汽车站),湘C76608~(湘乡市天门-湘潭市汽车西站),湘C80388~(湘乡市桂花-湘潭市汽车西站),湘C73926~(湘乡市壶天-湘潭市汽车西站),湘C75166~(湘乡市汽车站-湘潭市汽车西站),湘C75318~(湘乡市汽车站-湘潭市汽车西站),湘C75262~(湘乡市汽车站-湘潭市汽车西站),湘C75093~(湘乡市汽车站-湘潭市汽车西站),湘C75113~(湘乡市汽车站-湘潭市汽车西站),湘C75158~(湘乡市汽车站-湘潭市汽车西站)"); }},
            new HashMap<String, Object>(){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car","湘C14122~(湘潭市汽车西站-湘潭县日华),湘C16001~(湘潭市汽车西站-湘潭县石鼓),湘C13218~(湘潭市汽车西站-湘潭县石坝),湘C09729~(湘潭市汽车西站-湘乡市汽车站),湘C15096~(湘潭市汽车西站-湘潭县石鼓),湘C07195~(湘潭市汽车西站-湘潭县石潭),湘C14188~(湘潭市汽车西站-湘潭县花石),湘C14198~(湘潭市汽车西站-湘潭县花石),湘C14189~(湘潭市汽车西站-湘潭县花石),湘C12185~(湘潭市锰矿-湘潭市新湖),湘C09501~(湘潭市汽车西站-湘乡市汽车站),湘C15098~(湘潭市汽车西站-湘潭县石鼓),湘C12469~(湘潭市汽车西站-湘潭县石桐),湘C08072~(湘潭市汽车西站-湘潭县联兴),湘C09738~(湘潭市汽车西站-湘乡市汽车站),湘C09219~(湘潭市汽车西站-湘乡市汽车站),湘C13851~(湘潭市汽车西站-湘潭县石鼓),湘C08639~(湘潭市汽车西站-湘潭县泗路港),湘C07631~(湘潭市汽车西站-湘潭县高青),湘C14192~(湘潭市汽车西站-湘潭县花石),湘C15089~(湘潭市汽车西站-湘潭县石鼓),湘C14176~(湘潭市汽车西站-湘潭县花石),湘C13775~(湘潭市锰矿-湘潭市新湖),湘C13786~(湘潭市锰矿-湘潭县桐子坪),湘C09719~(湘潭市汽车西站-湘乡市汽车站),湘C14199~(湘潭市汽车西站-湘潭县歇马铜梁),湘C10883~(湘潭市汽车西站-湘潭县日华),湘C11293~(湘潭市汽车西站-湘潭县石鼓),湘C15086~(湘潭市汽车西站-湘潭县石鼓),湘C14202~(湘潭市汽车西站-湘潭县指路碑),湘C14081~(湘潭市汽车西站-湘潭县石潭坝),湘C12479~(湘潭市汽车西站-湘潭县环山),湘C13685~(湘潭市汽车西站-湘潭县环山),湘C09690~(湘潭市汽车西站-湘潭县歇马),湘C09289~(湘潭市汽车西站-湘潭县较场),湘C13766~(湘潭市锰矿-湘潭市燕山),湘C13779~(湘潭市锰矿-湘潭县桐子坪),湘C09698~(湘潭市汽车西站-湘潭县斗子塘),湘C14180~(湘潭市汽车西站-湘潭县花石),湘C13769~(湘潭市锰矿-湘潭县桐子坪),湘C13778~(湘潭市锰矿-湘潭市新湖),湘C16003~(湘潭市汽车西站-湘潭县石鼓),湘C15085~(湘潭市汽车西站-湘潭县石鼓),湘C14248~(湘潭市汽车西站-湘乡市白托),湘C14160~(湘潭市汽车西站-湘乡市汽车站),湘C09739~(湘潭市汽车西站-湘乡市汽车站),湘C09277~(湘潭市汽车西站-湘乡市汽车站),湘C09709~(湘潭市汽车西站-湘乡市汽车站),湘C15020~(湘潭市汽车西站-湘潭县石鼓),湘C15013~(湘潭市汽车西站-湘潭县石鼓),湘C15003~(湘潭市汽车西站-湘潭县石鼓),湘C15615~(湘潭市汽车西站-湘潭县联兴),湘C15609~(湘潭市汽车西站-湘乡市白托),湘C14190~(湘潭市汽车西站-湘潭县花石),湘C14179~(湘潭市汽车西站-湘潭县花石),湘C14182~(湘潭市汽车西站-湘潭县花石),湘C14187~(湘潭市汽车西站-湘潭县花石),湘C14249~(湘潭市汽车西站-湘乡市白托),湘C13785~(湘潭市锰矿-湘潭市燕山),湘C12196~(湘潭市锰矿-湘潭市燕山),湘C12156~(湘潭市锰矿-湘潭市新湖),湘C09625~(湘潭市汽车西站-湘潭县石潭),湘C07082~(湘潭市汽车西站-湘潭县石潭),湘C08391~(湘潭市汽车西站-湘潭县船形山),湘C07902~(湘潭市汽车西站-湘乡市汽车站),湘C09722~(湘潭市汽车西站-湘乡市汽车站),湘C09278~(湘潭市汽车西站-湘乡市汽车站),湘C09280~(湘潭市汽车西站-湘乡市汽车站),湘C09266~(湘潭市汽车西站-湘乡市汽车站),湘C09255~(湘潭市汽车西站-湘乡市汽车站),湘C14128~(湘潭市汽车西站-湘潭县石潭坝),湘C11699~(湘潭市汽车西站-湘潭县石鼓),湘C14082~(湘潭市汽车西站-湘潭县花石),湘C14107~(湘潭市汽车西站-湘潭县碧泉),湘C14119~(湘潭市汽车西站-湘潭县石鼓),湘C09725~(湘潭市汽车西站-湘潭县联兴),湘C10901~(湘潭市汽车西站-湘潭县歇马铜梁),湘C10150~(湘潭市汽车西站-湘潭县较场)"); }},
            new HashMap<String, Object>(){{ put("company","湘潭汽车运输有限公司韶山客运分公司"); put("type","县际"); put("car","湘C90950~(湘潭市汽车西站-韶山市汽车站),湘C91208~(韶山市汽车站-湘乡市泉塘),湘C90979~(湘潭市汽车西站-韶山市汽车站),湘C91155~(湘潭市汽车西站-韶山市汽车站),湘CV4293~(韶山市汽车站-湘乡市汽车站),湘C75109~(湘乡市泉塘-韶山市汽车站),湘C90965~(湘潭市汽车西站-韶山市汽车站),湘CV3270~(韶山市汽车站-湘乡市汽车站),湘C90978~(湘潭市汽车西站-韶山市汽车站),湘C90936~(韶山市汽车站-湘乡市泉塘),湘C91151~(韶山市汽车站-湘潭市汽车西站),湘C70638~(湘乡市汽车站-韶山市汽车站),湘C90955~(韶山市汽车站-湘乡市汽车站),湘C91159~(韶山市汽车站-湘潭市汽车西站),湘C90910~(湘潭市汽车西站-韶山市汽车站),湘C90851~(湘潭市汽车西站-韶山市汽车站),湘C90930~(湘潭市汽车西站-韶山市汽车站)"); }},
            new HashMap<String, Object>(){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car","湘C59712~(湘潭县汽车站-湘潭县石鼓),湘C56189~(湘潭县汽车站-湘潭县日华),湘C60025~(湘潭县楠竹山-湘潭县花石),湘C60105~(湘潭县汽车站-湘潭县茶恩寺),湘C56858~(湘潭县汽车站-湘潭县茶恩寺),湘C60113~(湘潭县茶恩寺-湘潭县汽车站),湘C60026~(湘潭县火口岭-湘潭县汽车站),湘C56152~(湘潭县云湖桥-湘潭县花石),湘C55825~(湘潭县汽车站-湘潭县石潭),湘C60109~(湘潭县万古桥-湘潭县汽车站),湘C57538~(湘潭县南冲-湘潭县汽车站),湘C58772~(湘潭县汽车站-湘潭县茶恩寺),湘C59102~(湘潭县郭家桥-湘潭县汽车站),湘C60106~(湘潭县万古桥-湘潭县汽车站),湘C60328~(湘潭县汽车站-湘潭县石潭),湘C58811~(湘潭县歇马-湘潭县汽车站),湘C58779~(湘潭县汽车站-湘潭县茶恩寺),湘C59073~(湘潭县汾水-湘潭县汽车站),湘C57529~(湘潭县坳才-湘潭县汽车站),湘C59187~(湘潭县汽车站-湘潭县花石),湘C60115~(湘潭县茶恩寺-湘潭县汽车站),湘C59071~(湘潭县汽车站-湘潭县石潭),湘C59132~(湘潭县船形-湘潭县汽车站),湘C58168~(湘潭县茶恩寺-湘潭县汽车站),湘C60117~(湘潭县茶恩寺-湘潭县汽车站),湘C59723~(湘潭县茶恩寺-湘潭县汽车站),湘C57286~(湘潭县汽车站-湘潭县花石),湘C60027~(湘潭县继述桥-湘潭县汽车站),湘C56837~(湘潭县汽车站-湘潭县花石),湘C57328~(湘潭县汽车站-湘潭县花石),湘C57577~(湘潭县汽车站-湘潭县花石),湘C59101~(湘潭县汽车站-湘潭县花石),湘C57581~(湘潭县歇马-湘潭县汽车站),湘C57530~(湘潭县石潭-湘潭县青山桥),湘C60323~(湘潭县踏莲桥-湘潭县汽车站),湘C58739~(湘潭县铁炉-湘潭县汽车站),湘C60367~(湘潭县汽车站-湘潭县石潭),湘C58926~(湘潭县汽车站-湘潭县石潭),湘C60327~(湘潭县汽车站-湘潭县石潭),湘C59875~(湘潭县汽车站-湘潭县石潭),湘C5M357~(湘潭县汽车站-湘潭县冷水湾),湘C60326~(湘潭县梅市-湘潭县汽车站),湘C60306~(湘潭县郭家桥-湘潭县汽车站),湘C60111~(湘潭县万古桥-湘潭县汽车站),湘C60037~(湘潭县星燎-湘潭县汽车站),湘C59197~(湘潭县继述桥-湘潭县汽车站),湘C58929~(湘潭县继述桥-湘潭县汽车站),湘C57557~(湘潭县汽车站-湘潭县坝塘),湘C59831~(湘潭县汽车站-湘潭县茶恩寺),湘C60126~(湘潭县汽车站-湘潭县茶恩寺),湘C60110~(湘潭县汽车站-湘潭县茶恩寺),湘C60133~(湘潭县汽车站-湘潭县茶恩寺),湘C56818~(湘潭县汽车站-湘潭县茶恩寺),湘C58256~(湘潭县茶恩寺-湘潭县汽车站),湘C57556~(湘潭县茶恩寺-湘潭县汽车站),湘C59730~(湘潭县茶恩寺-湘潭县汽车站),湘C60129~(湘潭县茶恩寺-湘潭县汽车站),湘C60031~(湘潭县碧泉-湘潭县汽车站),湘C59163~(湘潭县花石-湘潭县汽车站),湘C57718~(湘潭县花石-湘潭县汽车站),湘C57273~(湘潭县花石-湘潭县汽车站),湘C59860~(湘潭县汽车站-湘潭县花石),湘C56139~(湘潭县石鼓-湘潭县汽车站)"); }},
            new HashMap<String, Object>(){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县际"); put("car","湘C59563~(湘潭县上南-湘潭市汽车西站),湘C58833~(湘潭县方上桥-湘潭市汽车西站),湘C60336~(湘潭县鳌洲-湘潭市汽车西站),湘C60305~(湘潭县石潭-湘潭市汽车西站),湘C60321~(湘潭县石潭-湘潭市汽车西站),湘C60325~(湘潭县石潭-湘潭市汽车西站),湘C60118~(湘潭县歇马-湘潭市汽车西站),湘C58281~(湘潭县黄荆坪-湘潭市汽车西站),湘C60335~(湘潭县石潭-湘潭市汽车西站),湘C58863~(湘潭县桐子坪-湘潭市汽车西站),湘C60338~(湘潭县石潭-湘潭市汽车西站),湘C58115~(湘潭县辰山-湘潭市汽车西站),湘C60123~(湘潭县方上桥-湘潭市汽车西站),湘C60221~(湘潭县石潭-湘潭市汽车西站),湘C59635~(湘潭县平山岭-湘潭市汽车西站),湘C57381~(湘潭县花桥-湘潭市汽车西站),湘C60032~(湘潭县石鼓-湘潭市汽车西站),湘C60101~(湘潭县花桥-湘潭市汽车西站),湘C58035~(湘潭县石潭坝-湘潭市汽车西站),湘C57376~(湘潭县汽车站-韶山市汽车站),湘C57512~(湘潭县湘河村-湘潭市汽车西站),湘C60112~(湘潭县日华-湘潭市汽车西站),湘C60137~(湘潭县碳棚河-湘潭市汽车西站),湘C60127~(湘潭县双乐-湘潭市汽车西站),湘C59625~(湘潭县斗子塘-湘潭市汽车西站),湘C59572~(湘潭县景泉-湘潭市汽车西站),湘C60518~(湘潭县方上桥-湘潭市汽车西站),湘C59861~(湘潭县黄荆坪-湘潭市汽车西站),湘C59156~(湘潭县黄荆坪-湘潭市汽车西站),湘C60339~(湘潭县石潭-湘潭市汽车西站),湘C60317~(湘潭市汽车西站-湘潭县斗子塘),湘C56816~(湘潭县石潭-湘潭市汽车西站),湘C60376~(湘潭县石潭-湘潭市汽车西站),湘C60363~(湘潭县石潭-湘潭市汽车西站)"); }}
    );

    public static List<Map<String, Object>> ls = Arrays.asList(
            new HashMap<String, Object>(4){{ put("company","湘潭县公共汽车有限责任公司"); put("type","县内"); put("car"," (湘潭县茅亭-湘潭县汽车站)"); put("car_no","湘C57638"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县公共汽车有限责任公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县石鼓)"); put("car_no","湘C58821"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县公共汽车有限责任公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县茶恩寺)"); put("car_no","湘C58826"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县公共汽车有限责任公司"); put("type","县内"); put("car"," (湘潭县茶恩寺-湘潭县汽车站)"); put("car_no","湘C56501"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县公共汽车有限责任公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县茶恩寺)"); put("car_no","湘C58775"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县内"); put("car"," (湘潭县郭家桥-湘潭县汽车站)"); put("car_no","湘C58072"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县郭家桥)"); put("car_no","湘C58113"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县郭家桥)"); put("car_no","湘C58083"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县内"); put("car"," (湘潭县梅市-湘潭县汽车站)"); put("car_no","湘C58036"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县石潭)"); put("car_no","湘C55868"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县内"); put("car"," (湘潭县大坟山-湘潭县汽车站)"); put("car_no","湘C58128"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县内"); put("car"," (湘潭县高塘-湘潭县汽车站)"); put("car_no","湘C58109"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县黄荆坪)"); put("car_no","湘C56159"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县金石)"); put("car_no","湘C58017"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县内"); put("car"," (湘潭县金石-湘潭县汽车站)"); put("car_no","湘C57892"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县内"); put("car"," (湘潭县方上桥-湘潭县汽车站)"); put("car_no","湘C56883"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县内"); put("car"," (湘潭县石鼓-湘潭县汽车站)"); put("car_no","湘C56797"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县花石)"); put("car_no","湘C57876"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县内"); put("car"," (湘潭县花石-湘潭县汽车站)"); put("car_no","湘C56799"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县花石)"); put("car_no","湘C58705"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县内"); put("car"," (湘潭县花石-湘潭县汽车站)"); put("car_no","湘C58082"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县内"); put("car"," (湘潭县花石-湘潭县汽车站)"); put("car_no","湘C58719"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县内"); put("car"," (湘潭县花石-湘潭县汽车站)"); put("car_no","湘C58037"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县内"); put("car"," (湘潭县花石-湘潭县汽车站)"); put("car_no","湘C58199"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县内"); put("car"," (湘潭县花石-湘潭县汽车站)"); put("car_no","湘C58265"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县内"); put("car"," (湘潭县花石-湘潭县汽车站)"); put("car_no","湘C58081"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县内"); put("car"," (湘潭县花石-湘潭县汽车站)"); put("car_no","湘C57795"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县花石)"); put("car_no","湘C58097"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县内"); put("car"," (湘潭县花石-湘潭县汽车站)"); put("car_no","湘C58089"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县内"); put("car"," (湘潭县茶恩寺-湘潭县汽车站)"); put("car_no","湘C58010"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县茶恩寺)"); put("car_no","湘C57361"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县茶恩寺)"); put("car_no","湘C57563"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县茶恩寺)"); put("car_no","湘C58193"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县内"); put("car"," (湘潭县茶恩寺-湘潭县汽车站)"); put("car_no","湘C58189"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县茶恩寺)"); put("car_no","湘C58291"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县内"); put("car"," (湘潭县茶恩寺-湘潭县汽车站)"); put("car_no","湘C59656"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县茶恩寺)"); put("car_no","湘C58033"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县茶恩寺)"); put("car_no","湘C57560"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县内"); put("car"," (湘潭县茶恩寺-湘潭县汽车站)"); put("car_no","湘C58733"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县内"); put("car"," (湘潭县楠竹山-湘潭县汽车站)"); put("car_no","湘C56776"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县盐埠)"); put("car_no","湘C58702"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县内"); put("car"," (湘潭县景泉-湘潭县汽车站)"); put("car_no","湘C56833"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县内"); put("car"," (湘潭县东风水库-湘潭县汽车站)"); put("car_no","湘C57698"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县内"); put("car"," (湘潭县龙口石膏矿-湘潭县汽车站)"); put("car_no","湘C57591"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县内"); put("car"," (湘潭县日华-湘潭县花石)"); put("car_no","湘C58300"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县内"); put("car"," (湘潭县石坝-湘潭县汽车站)"); put("car_no","湘C57158"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县内"); put("car"," (湘潭县联兴-湘潭县汽车站)"); put("car_no","湘C58727"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县际"); put("car"," (湘潭县景泉-湘潭市汽车西站)"); put("car_no","湘C57215"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县际"); put("car"," (湘潭县景泉-湘潭市汽车西站)"); put("car_no","湘C57150"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县际"); put("car"," (湘潭县花桥-湘潭市汽车西站)"); put("car_no","湘C57053"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县际"); put("car"," (湘潭县毛塘坝-湘潭市汽车西站)"); put("car_no","湘C57681"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县际"); put("car"," (湘潭县石潭-湘潭市汽车西站)"); put("car_no","湘C56910"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县际"); put("car"," (湘潭县石潭-湘潭市汽车西站)"); put("car_no","湘C56880"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县际"); put("car"," (湘潭县湘河村-湘潭市汽车西站)"); put("car_no","湘C57066"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县际"); put("car"," (湘潭县四美-湘潭市汽车西站)"); put("car_no","湘C57528"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县际"); put("car"," (湘潭县瓦叶塘-湘潭市汽车西站)"); put("car_no","湘C57069"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县际"); put("car"," (湘潭县龙口石膏矿-湘潭市汽车西站)"); put("car_no","湘C56735"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县际"); put("car"," (湘潭县汽车站-湘乡市泉塘)"); put("car_no","湘C59823"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县际"); put("car"," (湘潭县斗子塘-湘潭市汽车西站)"); put("car_no","湘C58191"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县际"); put("car"," (湘潭县美德桥-湘潭市汽车西站)"); put("car_no","湘C58255"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县际"); put("car"," (湘乡市石坝-湘乡市汽车站)"); put("car_no","湘C57706"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县际"); put("car"," (湘潭县双马-湘潭市汽车西站)"); put("car_no","湘C57697"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县际"); put("car"," (湘潭县黄荆坪-湘潭市汽车西站)"); put("car_no","湘C57678"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县际"); put("car"," (湘潭县黄荆坪-湘潭市汽车西站)"); put("car_no","湘C57858"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县际"); put("car"," (湘潭县黄荆坪-湘潭市汽车西站)"); put("car_no","湘C57032"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县际"); put("car"," (湘潭县黄荆坪-湘潭市汽车西站)"); put("car_no","湘C58237"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县际"); put("car"," (湘潭县荆洲-湘潭市汽车西站)"); put("car_no","湘C56876"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县际"); put("car"," (湘潭市紫山-湘潭市汽车西站)"); put("car_no","湘C58277"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县日华)"); put("car_no","湘C56736"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县际"); put("car"," (湘潭县磷矿-湘潭市汽车西站)"); put("car_no","湘C58086"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县际"); put("car"," (湘潭县高泉-湘潭市汽车西站)"); put("car_no","湘C57693"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县际"); put("car"," (湘潭县金星-湘潭市汽车西站)"); put("car_no","湘C57598"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县际"); put("car"," (湘潭县盐埠-湘潭市汽车西站)"); put("car_no","湘C58263"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县际"); put("car"," (湘潭县盐埠-湘潭市汽车西站)"); put("car_no","湘C59679"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭县运输有限公司"); put("type","县际"); put("car"," (湘潭县盐埠-湘潭市汽车西站)"); put("car_no","湘C59736"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市汽车站-湘乡市南郑)"); put("car_no","湘C77721"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市九雁塘-湘乡市汽车站)"); put("car_no","湘C75992"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市汽车站-湘乡市九雁塘)"); put("car_no","湘C75991"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市大乐-湘乡市汽车站)"); put("car_no","湘C77785"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市朝阳-湘乡市汽车站)"); put("car_no","湘C77105"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市汽车站-湘乡市朝阳)"); put("car_no","湘C77023"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市壶天南岳-湘乡市日新)"); put("car_no","湘C75862"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市汽车站-湘乡市清江)"); put("car_no","湘C76926"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市汽车站-湘乡市清江)"); put("car_no","湘C76936"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市大湖-湘乡市汽车站)"); put("car_no","湘C73936"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市汽车站-湘乡市青皮)"); put("car_no","湘C76375"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市汽车站-湘乡市毛田)"); put("car_no","湘C75583"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市汽车站-湘乡市毛田)"); put("car_no","湘C77005"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市毛田-湘乡市汽车站)"); put("car_no","湘C76952"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市云居-湘乡市汽车站)"); put("car_no","湘C75925"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市壶天-湘乡市汽车站)"); put("car_no","湘C78278"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市壶天-湘乡市汽车站)"); put("car_no","湘C75296"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市壶天-湘乡市汽车站)"); put("car_no","湘C78338"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市壶天-湘乡市汽车站)"); put("car_no","湘C75261"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市壶天-湘乡市汽车站)"); put("car_no","湘C78088"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市壶天-湘乡市汽车站)"); put("car_no","湘C75293"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市壶天-湘乡市汽车站)"); put("car_no","湘C75963"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市壶天-湘乡市汽车站)"); put("car_no","湘C75986"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市壶天-湘乡市汽车站)"); put("car_no","湘C76281"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市汽车站-湘乡市壶天)"); put("car_no","湘C75967"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市汽车站-湘乡市壶天)"); put("car_no","湘C79588"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市汽车站-湘乡市壶天)"); put("car_no","湘C77118"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市壶天-湘乡市汽车站)"); put("car_no","湘C75805"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市壶天-湘乡市汽车站)"); put("car_no","湘C75850"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市壶天-湘乡市汽车站)"); put("car_no","湘C79088"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市壶天-湘乡市汽车站)"); put("car_no","湘C77763"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市壶天-湘乡市汽车站)"); put("car_no","湘C75851"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市壶天-湘乡市汽车站)"); put("car_no","湘C78038"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市壶天-湘乡市汽车站)"); put("car_no","湘C77786"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市壶天-湘乡市汽车站)"); put("car_no","湘C75031"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市汽车站-湘乡市壶天)"); put("car_no","湘C75972"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市壶天-湘乡市汽车站)"); put("car_no","湘C73612"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市壶天-湘乡市汽车站)"); put("car_no","湘C73666"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市壶天-湘乡市汽车站)"); put("car_no","湘C77790"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市于塘-湘乡市汽车站)"); put("car_no","湘C73508"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市桂花-湘乡市汽车站)"); put("car_no","湘C75231"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市桂花-湘乡市汽车站)"); put("car_no","湘C77029"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市汽车站-湘乡市桂花)"); put("car_no","湘C77038"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市石桥-湘乡市汽车站)"); put("car_no","湘C76935"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市石桥-湘乡市汽车站)"); put("car_no","湘C76269"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市石桥-湘乡市汽车站)"); put("car_no","湘C77782"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市石桥-湘乡市汽车站)"); put("car_no","湘C77195"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市石桥-湘乡市汽车站)"); put("car_no","湘C76231"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市壶天南岳-湘乡市汽车站)"); put("car_no","湘C75879"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市白银村-湘乡市汽车站)"); put("car_no","湘C76520"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市石坝-湘乡市汽车站)"); put("car_no","湘C75305"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市石坝-湘乡市汽车站)"); put("car_no","湘C76983"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市壶天合东-湘乡市汽车站)"); put("car_no","湘C77163"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市杜家坪-湘乡市汽车站)"); put("car_no","湘C76239"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市汽车站-湘乡市横铺)"); put("car_no","湘C75181"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市横铺-湘乡市汽车站)"); put("car_no","湘C77858"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市横铺-湘乡市汽车站)"); put("car_no","湘C75213"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市汽车站-湘乡市横铺)"); put("car_no","湘C73882"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市汽车站-湘乡市横铺)"); put("car_no","湘C75538"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市汽车站-湘乡市横铺)"); put("car_no","湘C75199"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市横铺-湘乡市汽车站)"); put("car_no","湘C77771"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市横铺-湘乡市汽车站)"); put("car_no","湘C73885"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市横铺-湘乡市汽车站)"); put("car_no","湘C73933"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市汽车站-湘乡市横铺)"); put("car_no","湘C75009"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市新跃-湘乡市汽车站)"); put("car_no","湘C75982"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市汽车站-湘乡市茶杯)"); put("car_no","湘C79888"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市月山湾-湘乡市汽车站)"); put("car_no","湘C76257"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市月山湾-湘乡市汽车站)"); put("car_no","湘C78028"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市汽车站-湘乡市月山湾)"); put("car_no","湘C75987"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市月山湾-湘乡市汽车站)"); put("car_no","湘C75865"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市翻江-湘乡市棋梓)"); put("car_no","湘C75837"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市洪塘-湘乡市汽车站)"); put("car_no","湘C77787"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市汽车站-湘乡市苏坡)"); put("car_no","湘C79668"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市汽车站-湘乡市苏坡)"); put("car_no","湘C75859"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市马坪-湘乡市汽车站)"); put("car_no","湘C75803"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市汽车站-湘乡市马坪)"); put("car_no","湘C73685"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市马坪-湘乡市汽车站)"); put("car_no","湘C75869"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市汽车站-湘乡市马坪)"); put("car_no","湘C75125"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市汽车站-湘乡市马坪)"); put("car_no","湘C75192"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市汽车站-湘乡市马坪)"); put("car_no","湘C75126"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市马坪-湘乡市汽车站)"); put("car_no","湘C73265"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市马坪-湘乡市汽车站)"); put("car_no","湘C73562"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市马坪-湘乡市汽车站)"); put("car_no","湘C73687"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市汽车站-湘乡市马坪)"); put("car_no","湘C73679"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市汽车站-湘乡市马坪)"); put("car_no","湘C75260"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市棋梓-湘乡市汽车站)"); put("car_no","湘C75130"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市汽车站-湘乡市棋梓)"); put("car_no","湘C75096"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市汽车站-湘乡市棋梓)"); put("car_no","湘C75239"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市棋梓-湘乡市汽车站)"); put("car_no","湘C75300"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市棋梓-湘乡市汽车站)"); put("car_no","湘C76268"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市汽车站-湘乡市棋梓)"); put("car_no","湘C75228"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市棋梓-湘乡市汽车站)"); put("car_no","湘C75075"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市棋梓-湘乡市汽车站)"); put("car_no","湘C76276"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市汽车站-湘乡市棋梓)"); put("car_no","湘C75266"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市棋梓-湘乡市汽车站)"); put("car_no","湘C75371"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市棋梓-湘乡市汽车站)"); put("car_no","湘C75265"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市棋梓-湘乡市汽车站)"); put("car_no","湘C75316"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市棋梓-湘乡市汽车站)"); put("car_no","湘C75095"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市棋梓-湘乡市汽车站)"); put("car_no","湘C77737"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市棋梓-湘乡市汽车站)"); put("car_no","湘C75221"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市汽车站-湘乡市棋梓)"); put("car_no","湘C75032"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市汽车站-湘乡市棋梓)"); put("car_no","湘C75111"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市汽车站-湘乡市棋梓)"); put("car_no","湘C75255"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市汽车站-湘乡市棋梓)"); put("car_no","湘C75220"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市棋梓-湘乡市汽车站)"); put("car_no","湘C76256"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市棋梓-湘乡市汽车站)"); put("car_no","湘C75332"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市棋梓-湘乡市汽车站)"); put("car_no","湘C73925"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市棋梓-湘乡市汽车站)"); put("car_no","湘C75106"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市棋梓-湘乡市汽车站)"); put("car_no","湘C75223"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市汽车站-湘乡市棋梓)"); put("car_no","湘C75205"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市棋梓-湘乡市汽车站)"); put("car_no","湘C75020"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市汽车站-湘乡市棋梓)"); put("car_no","湘C75007"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市汽车站-湘乡市棋梓)"); put("car_no","湘C75076"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市汽车站-湘乡市棋梓)"); put("car_no","湘C75091"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市棋梓-湘乡市汽车站)"); put("car_no","湘C75207"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市汽车站-湘乡市楠竹口)"); put("car_no","湘C76292"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市榨坪-湘乡市汽车站)"); put("car_no","湘C76913"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市岐山-湘乡市汽车站)"); put("car_no","湘C76925"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市岐山-湘乡市汽车站)"); put("car_no","湘C76212"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市岐山-湘乡市汽车站)"); put("car_no","湘C73708"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市邓氏路口-湘乡市汽车站)"); put("car_no","湘C75856"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市邓氏路口-湘乡市汽车站)"); put("car_no","湘C75102"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市低坪-湘乡市汽车站)"); put("car_no","湘C75866"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市汽车站-湘乡市曾家山)"); put("car_no","湘C76253"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市高维-湘乡市汽车站)"); put("car_no","湘C76280"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市汽车站-湘乡市大杉)"); put("car_no","湘C75067"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市大杉-湘乡市汽车站)"); put("car_no","湘C77028"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市红石-湘乡市汽车站)"); put("car_no","湘C75115"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市小车-湘乡市汽车站)"); put("car_no","湘C76985"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市马龙-湘乡市汽车站)"); put("car_no","湘C76311"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市棋梓-湘乡市曾家山)"); put("car_no","湘C76221"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市棋梓-湘乡市曾家山)"); put("car_no","湘C76232"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市日新-湘乡市岐山)"); put("car_no","湘C75326"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市日新-湘乡市岐山)"); put("car_no","湘C76273"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市日新-湘乡市岐山)"); put("car_no","湘C76283"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市白石-湘乡市汽车站)"); put("car_no","湘C75129"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市酒铺-湘乡市汽车站)"); put("car_no","湘C76265"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市汽车站-湘乡市金龙)"); put("car_no","湘C73569"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县内"); put("car"," (湘乡市枚下-湘乡市汽车站)"); put("car_no","湘C75876"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县际"); put("car"," (湘乡市汽车站-湘潭市汽车西站)"); put("car_no","湘C75283"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县际"); put("car"," (湘乡市汽车站-湘潭市汽车西站)"); put("car_no","湘C75225"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县际"); put("car"," (湘乡市汽车站-湘潭市汽车西站)"); put("car_no","湘C75317"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县际"); put("car"," (湘乡市汽车站-湘潭市汽车西站)"); put("car_no","湘C75299"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县际"); put("car"," (湘乡市汽车站-湘潭市汽车西站)"); put("car_no","湘C75127"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县际"); put("car"," (湘乡市汽车站-湘潭市汽车西站)"); put("car_no","湘C73951"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县际"); put("car"," (湘乡市汽车站-湘潭市汽车西站)"); put("car_no","湘C75169"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县际"); put("car"," (湘乡市汽车站-湘潭市汽车西站)"); put("car_no","湘C72502"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县际"); put("car"," (湘乡市汽车站-湘潭市汽车西站)"); put("car_no","湘C75258"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县际"); put("car"," (湘乡市汽车站-湘潭市汽车西站)"); put("car_no","湘C75166"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县际"); put("car"," (湘乡市汽车站-湘潭市汽车西站)"); put("car_no","湘C75318"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县际"); put("car"," (湘乡市汽车站-湘潭市汽车西站)"); put("car_no","湘C75262"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县际"); put("car"," (湘乡市汽车站-湘潭市汽车西站)"); put("car_no","湘C75093"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县际"); put("car"," (湘乡市汽车站-湘潭市汽车西站)"); put("car_no","湘C75113"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县际"); put("car"," (湘乡市汽车站-湘潭市汽车西站)"); put("car_no","湘C75158"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县际"); put("car"," (湘乡市汽车站-湘潭市汽车西站)"); put("car_no","湘C75107"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县际"); put("car"," (湘乡市汽车站-湘潭市汽车西站)"); put("car_no","湘C75285"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县际"); put("car"," (湘乡市汽车站-湘潭市汽车西站)"); put("car_no","湘C75282"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县际"); put("car"," (湘乡市汽车站-湘潭市汽车西站)"); put("car_no","湘C73972"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县际"); put("car"," (湘乡市坪花-湘潭市汽车西站)"); put("car_no","湘C78528"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县际"); put("car"," (湘潭县茶佩-湘潭市汽车西站)"); put("car_no","湘C76275"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县际"); put("car"," (湘潭县环山-湘潭市汽车西站)"); put("car_no","湘C78378"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县际"); put("car"," (湘乡市汽车站-湘潭县汽车站)"); put("car_no","湘C73702"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县际"); put("car"," (湘乡市泉塘-湘潭县汽车站)"); put("car_no","湘C77158"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县际"); put("car"," (湘乡市汽车站-湘潭县汽车站)"); put("car_no","湘C76391"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县际"); put("car"," (湘乡市汽车站-湘潭县汽车站)"); put("car_no","湘C77008"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县际"); put("car"," (湘乡市泉塘-湘潭县汽车站)"); put("car_no","湘C76991"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县际"); put("car"," (湘乡市泉塘-湘潭县汽车站)"); put("car_no","湘C76323"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县际"); put("car"," (湘乡市泉塘-湘潭县汽车站)"); put("car_no","湘C77136"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县际"); put("car"," (湘乡市桂花-湘潭市汽车西站)"); put("car_no","湘C80388"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县际"); put("car"," (湘乡市天门-湘潭市汽车西站)"); put("car_no","湘C76608"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县际"); put("car"," (湘乡市白云石矿-湘潭市下摄司)"); put("car_no","湘C75552"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县际"); put("car"," (湘乡市毛田-湘潭市汽车西站)"); put("car_no","湘C75910"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县际"); put("car"," (湘乡市水府庙-湘潭市汽车西站)"); put("car_no","湘C76698"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县际"); put("car"," (湘乡市马坪-湘潭市汽车西站)"); put("car_no","湘C75182"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县际"); put("car"," (湘乡市壶天-湘潭市汽车西站)"); put("car_no","湘C73926"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘乡客运分公司"); put("type","县际"); put("car"," (湘潭县歇马-湘潭市株易路口)"); put("car_no","湘C73521"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县南冲-湘潭县汽车站)"); put("car_no","湘C57538"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县郭家桥-湘潭县汽车站)"); put("car_no","湘C60306"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县梅市-湘潭县汽车站)"); put("car_no","湘C60326"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县冷水湾)"); put("car_no","湘C5M357"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县石潭)"); put("car_no","湘C59071"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县石潭)"); put("car_no","湘C60328"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县石潭)"); put("car_no","湘C55825"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县石潭)"); put("car_no","湘C59875"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县石潭)"); put("car_no","湘C60327"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县石潭)"); put("car_no","湘C58926"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县石潭)"); put("car_no","湘C60367"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县日华)"); put("car_no","湘C56189"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县继述桥-湘潭县汽车站)"); put("car_no","湘C58929"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县继述桥-湘潭县汽车站)"); put("car_no","湘C59197"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县继述桥-湘潭县汽车站)"); put("car_no","湘C60027"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县铁炉-湘潭县汽车站)"); put("car_no","湘C58739"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县云湖桥-湘潭县花石)"); put("car_no","湘C56152"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县郭家桥-湘潭县汽车站)"); put("car_no","湘C59102"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县歇马-湘潭县汽车站)"); put("car_no","湘C57581"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县歇马-湘潭县汽车站)"); put("car_no","湘C58811"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县坳才-湘潭县汽车站)"); put("car_no","湘C57529"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县楠竹山-湘潭县花石)"); put("car_no","湘C60025"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县石鼓)"); put("car_no","湘C59712"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县石鼓-湘潭县汽车站)"); put("car_no","湘C56139"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县花石)"); put("car_no","湘C59187"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县花石)"); put("car_no","湘C59860"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县花石)"); put("car_no","湘C57577"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县花石-湘潭县汽车站)"); put("car_no","湘C57273"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县花石)"); put("car_no","湘C56837"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县花石)"); put("car_no","湘C57328"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县花石-湘潭县汽车站)"); put("car_no","湘C57718"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县花石)"); put("car_no","湘C57286"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县花石-湘潭县汽车站)"); put("car_no","湘C59163"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县花石)"); put("car_no","湘C59101"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县茶恩寺)"); put("car_no","湘C58772"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县茶恩寺)"); put("car_no","湘C58779"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县茶恩寺-湘潭县汽车站)"); put("car_no","湘C60115"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县茶恩寺-湘潭县汽车站)"); put("car_no","湘C58168"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县茶恩寺-湘潭县汽车站)"); put("car_no","湘C60117"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县茶恩寺-湘潭县汽车站)"); put("car_no","湘C59723"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县茶恩寺)"); put("car_no","湘C60105"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县茶恩寺-湘潭县汽车站)"); put("car_no","湘C60113"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县茶恩寺)"); put("car_no","湘C56858"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县茶恩寺)"); put("car_no","湘C59831"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县茶恩寺)"); put("car_no","湘C60126"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县茶恩寺)"); put("car_no","湘C60110"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县茶恩寺)"); put("car_no","湘C60133"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县茶恩寺)"); put("car_no","湘C56818"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县茶恩寺-湘潭县汽车站)"); put("car_no","湘C58256"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县茶恩寺-湘潭县汽车站)"); put("car_no","湘C57556"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县茶恩寺-湘潭县汽车站)"); put("car_no","湘C59730"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县茶恩寺-湘潭县汽车站)"); put("car_no","湘C60129"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县火口岭-湘潭县汽车站)"); put("car_no","湘C60026"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县船形-湘潭县汽车站)"); put("car_no","湘C59132"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县汾水-湘潭县汽车站)"); put("car_no","湘C59073"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县碧泉-湘潭县汽车站)"); put("car_no","湘C60031"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县汽车站-湘潭县坝塘)"); put("car_no","湘C57557"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县万古桥-湘潭县汽车站)"); put("car_no","湘C60111"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县万古桥-湘潭县汽车站)"); put("car_no","湘C60106"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县万古桥-湘潭县汽车站)"); put("car_no","湘C60109"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县星燎-湘潭县汽车站)"); put("car_no","湘C60037"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县踏莲桥-湘潭县汽车站)"); put("car_no","湘C60323"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县内"); put("car"," (湘潭县石潭-湘潭县青山桥)"); put("car_no","湘C57530"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县际"); put("car"," (湘潭县方上桥-湘潭市汽车西站)"); put("car_no","湘C60518"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县际"); put("car"," (湘潭县方上桥-湘潭市汽车西站)"); put("car_no","湘C58833"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县际"); put("car"," (湘潭县方上桥-湘潭市汽车西站)"); put("car_no","湘C60123"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县际"); put("car"," (湘潭县景泉-湘潭市汽车西站)"); put("car_no","湘C59572"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县际"); put("car"," (湘潭县石鼓-湘潭市汽车西站)"); put("car_no","湘C60032"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县际"); put("car"," (湘潭县石潭-湘潭市汽车西站)"); put("car_no","湘C60321"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县际"); put("car"," (湘潭县石潭-湘潭市汽车西站)"); put("car_no","湘C60305"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县际"); put("car"," (湘潭县石潭-湘潭市汽车西站)"); put("car_no","湘C60339"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县际"); put("car"," (湘潭县石潭-湘潭市汽车西站)"); put("car_no","湘C56816"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县际"); put("car"," (湘潭县石潭-湘潭市汽车西站)"); put("car_no","湘C60376"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县际"); put("car"," (湘潭县石潭-湘潭市汽车西站)"); put("car_no","湘C60363"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县际"); put("car"," (湘潭县石潭-湘潭市汽车西站)"); put("car_no","湘C60325"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县际"); put("car"," (湘潭县石潭-湘潭市汽车西站)"); put("car_no","湘C60335"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县际"); put("car"," (湘潭县石潭-湘潭市汽车西站)"); put("car_no","湘C60338"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县际"); put("car"," (湘潭县石潭-湘潭市汽车西站)"); put("car_no","湘C60221"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县际"); put("car"," (湘潭县碳棚河-湘潭市汽车西站)"); put("car_no","湘C60137"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县际"); put("car"," (湘潭县湘河村-湘潭市汽车西站)"); put("car_no","湘C57512"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县际"); put("car"," (湘潭县花桥-湘潭市汽车西站)"); put("car_no","湘C60101"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县际"); put("car"," (湘潭县花桥-湘潭市汽车西站)"); put("car_no","湘C57381"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县际"); put("car"," (湘潭县平山岭-湘潭市汽车西站)"); put("car_no","湘C59635"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县斗子塘)"); put("car_no","湘C60317"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县际"); put("car"," (湘潭县汽车站-韶山市汽车站)"); put("car_no","湘C57376"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县际"); put("car"," (湘潭县歇马-湘潭市汽车西站)"); put("car_no","湘C60118"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县际"); put("car"," (湘潭县鳌洲-湘潭市汽车西站)"); put("car_no","湘C60336"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县际"); put("car"," (湘潭县上南-湘潭市汽车西站)"); put("car_no","湘C59563"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县际"); put("car"," (湘潭县日华-湘潭市汽车西站)"); put("car_no","湘C60112"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县际"); put("car"," (湘潭县石潭坝-湘潭市汽车西站)"); put("car_no","湘C58035"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县际"); put("car"," (湘潭县黄荆坪-湘潭市汽车西站)"); put("car_no","湘C59156"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县际"); put("car"," (湘潭县黄荆坪-湘潭市汽车西站)"); put("car_no","湘C59861"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县际"); put("car"," (湘潭县黄荆坪-湘潭市汽车西站)"); put("car_no","湘C58281"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县际"); put("car"," (湘潭县斗子塘-湘潭市汽车西站)"); put("car_no","湘C59625"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县际"); put("car"," (湘潭县辰山-湘潭市汽车西站)"); put("car_no","湘C58115"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县际"); put("car"," (湘潭县双乐-湘潭市汽车西站)"); put("car_no","湘C60127"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司湘潭县客运分公司"); put("type","县际"); put("car"," (湘潭县桐子坪-湘潭市汽车西站)"); put("car_no","湘C58863"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘乡市汽车站)"); put("car_no","湘C09738"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘乡市汽车站)"); put("car_no","湘C09501"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘乡市汽车站)"); put("car_no","湘C09729"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘乡市汽车站)"); put("car_no","湘C09255"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘乡市汽车站)"); put("car_no","湘C09266"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘乡市汽车站)"); put("car_no","湘C09280"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘乡市汽车站)"); put("car_no","湘C09278"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘乡市汽车站)"); put("car_no","湘C09722"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘乡市汽车站)"); put("car_no","湘C07902"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘乡市汽车站)"); put("car_no","湘C09709"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘乡市汽车站)"); put("car_no","湘C09277"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘乡市汽车站)"); put("car_no","湘C09739"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘乡市汽车站)"); put("car_no","湘C14160"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘乡市汽车站)"); put("car_no","湘C09719"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘乡市汽车站)"); put("car_no","湘C09219"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县石桐)"); put("car_no","湘C12469"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县泗路港)"); put("car_no","湘C08639"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县石鼓)"); put("car_no","湘C16003"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县石鼓)"); put("car_no","湘C15096"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县石鼓)"); put("car_no","湘C11699"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县石鼓)"); put("car_no","湘C15098"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县石鼓)"); put("car_no","湘C14119"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县石鼓)"); put("car_no","湘C13851"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县石鼓)"); put("car_no","湘C15086"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县石鼓)"); put("car_no","湘C11293"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县石鼓)"); put("car_no","湘C16001"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县石鼓)"); put("car_no","湘C15089"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县石鼓)"); put("car_no","湘C15003"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县石鼓)"); put("car_no","湘C15013"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县石鼓)"); put("car_no","湘C15020"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县石鼓)"); put("car_no","湘C15085"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县石潭)"); put("car_no","湘C07082"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县石潭)"); put("car_no","湘C07195"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县石潭)"); put("car_no","湘C09625"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县环山)"); put("car_no","湘C13685"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县环山)"); put("car_no","湘C12479"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘乡市白托)"); put("car_no","湘C15609"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘乡市白托)"); put("car_no","湘C14249"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘乡市白托)"); put("car_no","湘C14248"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县斗子塘)"); put("car_no","湘C09698"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县歇马)"); put("car_no","湘C09690"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县石坝)"); put("car_no","湘C13218"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市锰矿-湘潭市燕山)"); put("car_no","湘C12196"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市锰矿-湘潭市燕山)"); put("car_no","湘C13785"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市锰矿-湘潭市燕山)"); put("car_no","湘C13766"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县联兴)"); put("car_no","湘C08072"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县花石)"); put("car_no","湘C14190"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县花石)"); put("car_no","湘C14179"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县花石)"); put("car_no","湘C14182"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县花石)"); put("car_no","湘C14187"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县花石)"); put("car_no","湘C14082"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县联兴)"); put("car_no","湘C09725"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县花石)"); put("car_no","湘C14188"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县花石)"); put("car_no","湘C14198"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县花石)"); put("car_no","湘C14189"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县联兴)"); put("car_no","湘C15615"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县花石)"); put("car_no","湘C14192"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县花石)"); put("car_no","湘C14176"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县花石)"); put("car_no","湘C14180"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县石潭坝)"); put("car_no","湘C14081"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县石潭坝)"); put("car_no","湘C14128"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县指路碑)"); put("car_no","湘C14202"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县歇马铜梁)"); put("car_no","湘C14199"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县歇马铜梁)"); put("car_no","湘C10901"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市锰矿-湘潭县桐子坪)"); put("car_no","湘C13786"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市锰矿-湘潭县桐子坪)"); put("car_no","湘C13779"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市锰矿-湘潭县桐子坪)"); put("car_no","湘C13769"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县高青)"); put("car_no","湘C07631"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县日华)"); put("car_no","湘C10883"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县日华)"); put("car_no","湘C14122"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县较场)"); put("car_no","湘C10150"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县较场)"); put("car_no","湘C09289"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县船形山)"); put("car_no","湘C08391"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-湘潭县碧泉)"); put("car_no","湘C14107"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市锰矿-湘潭市新湖)"); put("car_no","湘C12156"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市锰矿-湘潭市新湖)"); put("car_no","湘C13778"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市锰矿-湘潭市新湖)"); put("car_no","湘C12185"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司西站客运分公司"); put("type","县际"); put("car"," (湘潭市锰矿-湘潭市新湖)"); put("car_no","湘C13775"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司韶山客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-韶山市汽车站)"); put("car_no","湘C90950"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司韶山客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-韶山市汽车站)"); put("car_no","湘C90930"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司韶山客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-韶山市汽车站)"); put("car_no","湘C90979"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司韶山客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-韶山市汽车站)"); put("car_no","湘C91155"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司韶山客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-韶山市汽车站)"); put("car_no","湘C90965"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司韶山客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-韶山市汽车站)"); put("car_no","湘C90978"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司韶山客运分公司"); put("type","县际"); put("car"," (韶山市汽车站-湘潭市汽车西站)"); put("car_no","湘C91151"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司韶山客运分公司"); put("type","县际"); put("car"," (韶山市汽车站-湘潭市汽车西站)"); put("car_no","湘C91159"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司韶山客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-韶山市汽车站)"); put("car_no","湘C90851"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司韶山客运分公司"); put("type","县际"); put("car"," (湘潭市汽车西站-韶山市汽车站)"); put("car_no","湘C90910"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司韶山客运分公司"); put("type","县际"); put("car"," (韶山市汽车站-湘乡市汽车站)"); put("car_no","湘CV4293"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司韶山客运分公司"); put("type","县际"); put("car"," (湘乡市汽车站-韶山市汽车站)"); put("car_no","湘C70638"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司韶山客运分公司"); put("type","县际"); put("car"," (韶山市汽车站-湘乡市汽车站)"); put("car_no","湘C90955"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司韶山客运分公司"); put("type","县际"); put("car"," (韶山市汽车站-湘乡市汽车站)"); put("car_no","湘CV3270"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司韶山客运分公司"); put("type","县际"); put("car"," (湘乡市泉塘-韶山市汽车站)"); put("car_no","湘C75109"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司韶山客运分公司"); put("type","县际"); put("car"," (韶山市汽车站-湘乡市泉塘)"); put("car_no","湘C90936"); }},
            new HashMap<String, Object>(4){{ put("company","湘潭汽车运输有限公司韶山客运分公司"); put("type","县际"); put("car"," (韶山市汽车站-湘乡市泉塘)"); put("car_no","湘C91208"); }}
    );
}
