server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lan_test?serverTimezone=GMT
    username: root
    password: root
mybatis:
  type-aliases-package: cn.itcast.service.pojo
