server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/mybatis?serverTimezone=GMT #你学习mybatis时，使用的数据库地址
    username: root
    password: root
mybatis:
  type-aliases-package: cn.itcast.service.pojo
