spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/jpa
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
#     更新或者创建数据表结构
      ddl-auto: none
#    控制台显示SQL
    show-sql: true
